### ISSUE TITLE
I have getting run time error while using "react-snowfall"

### ISSUE THREAD

**Issue by randikaa** [cahilfoley/react-snowfall#74]
ERROR
Target container is not a DOM element.
    at Object.render (http://localhost:3003/static/js/bundle.js:31465:15)
    at App (http://localhost:3003/main.3b49550e53b6958dfaea.hot-update.js:28:42)
    at renderWithHooks (http://localhost:3003/static/js/bundle.js:20018:22)
    at mountIndeterminateComponent (http://localhost:3003/static/js/bundle.js:23302:17)
    at beginWork (http://localhost:3003/static/js/bundle.js:24598:20)
    at HTMLUnknownElement.callCallback (http://localhost:3003/static/js/bundle.js:9614:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3003/static/js/bundle.js:9658:20)
    at invokeGuardedCallback (http://localhost:3003/static/js/bundle.js:9715:35)
    at beginWork$1 (http://localhost:3003/static/js/bundle.js:29579:11)
    at performUnitOfWork (http://localhost:3003/static/js/bundle.js:28827:16)

**Comment by cahilfoley** [comment]
Hey there, is there any chance you could provide a reproduction of this so I can narrow down the issue?

Really appreciate the help!
